// TB DOT Clinic Data — Ogun State, Nigeria
const clinicData = [
  {
    id: 1,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "SABO AGURA",
    name: "ARUBA",
    signage: "Yes",
    locationType: "Semi-Urban",
    status: "Located and Open",
    lat: 6.825422,
    lng: 3.655275
  },
  {
    id: 2,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "ODELEMO",
    name: "EMUREN",
    signage: "No",
    locationType: "Rural",
    status: "Located and Open",
    lat: 6.696772,
    lng: 3.617214
  },
  {
    id: 3,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "ITUNSOKU",
    name: "ITUNSOKU",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.841372,
    lng: 3.646416
  },
  {
    id: 4,
    state: "OGUN",
    lga: "SABO GRA",
    ward: "SABO GRA",
    name: "SABO GRA",
    signage: "No",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.836423,
    lng: 3.633725
  },
  {
    id: 5,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "SABO AGURA",
    name: "SABO AGURA",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.832458,
    lng: 3.647943
  },
  {
    id: 6,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "OGIJO",
    name: "AFISURU HEALTH CENTRE",
    signage: "Yes",
    locationType: "Semi-Urban",
    status: "Located and Open",
    lat: 6.716394,
    lng: 3.521219
  },
  {
    id: 7,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "OGIJO",
    name: "OGIJO HC",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.70418,
    lng: 3.511011
  },
  {
    id: 8,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "OGIJO",
    name: "AJEGUNLE",
    signage: "No",
    locationType: "Rural",
    status: "Located and Open",
    lat: 6.692734,
    lng: 3.494852
  },
  {
    id: 9,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "OGIJO",
    name: "OGEDE",
    signage: "Yes",
    locationType: "Rural",
    status: "Located and Open",
    lat: 6.716801,
    lng: 3.481645
  },
  {
    id: 10,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "AIYEGBAMI",
    name: "AIYEGBAMI",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.837634,
    lng: 3.652595
  },
  {
    id: 11,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "BATORO",
    name: "BATORO",
    signage: "No",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.844058,
    lng: 3.650475
  },
  {
    id: 12,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "IPOJI",
    name: "IPOJI",
    signage: "No",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.845309,
    lng: 3.652082
  },
  {
    id: 13,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "SOYINDO",
    name: "LEGACY HC",
    signage: "No",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.852567,
    lng: 3.654561
  },
  {
    id: 14,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "AGBOWA",
    name: "AGBOWA IBIDO",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.851995,
    lng: 3.647027
  },
  {
    id: 15,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "AJAKA",
    name: "AJAKA",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.853548,
    lng: 3.635688
  },
  {
    id: 16,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "IJAGBA",
    name: "IJAGBA",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.847589,
    lng: 3.645721
  },
  {
    id: 17,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "LATAWA",
    name: "LATAWA",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.844648,
    lng: 3.644424
  },
  {
    id: 18,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "ITUNSOKU",
    name: "AMODU ALOWOMATANA",
    signage: "No",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.846502,
    lng: 3.647329
  },
  {
    id: 19,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "ISOTE",
    name: "ISOTE",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.847996,
    lng: 3.641809
  },
  {
    id: 20,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "OGIJO",
    name: "SOTUBO",
    signage: "Yes",
    locationType: "Semi-Urban",
    status: "Located and Open",
    lat: 6.807533,
    lng: 3.584403
  },
  {
    id: 21,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "SIMAWA",
    name: "SIMAWA",
    signage: "Yes",
    locationType: "Rural",
    status: "Located and Open",
    lat: 6.774019,
    lng: 3.50171
  },
  {
    id: 22,
    state: "OGUN",
    lga: "OGUN",
    ward: "OGIJO",
    name: "LIKOSI",
    signage: "Yes",
    locationType: "Semi-Urban",
    status: "Located and Open",
    lat: 6.761471,
    lng: 3.536275
  },
  {
    id: 23,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "SABO AGURA",
    name: "OWODE EPOTA",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.822969,
    lng: 3.633803
  },
  {
    id: 24,
    state: "OGUN",
    lga: "SAGAMU",
    ward: "OJUMELE",
    name: "MAKUN OJUMELE",
    signage: "Yes",
    locationType: "Urban",
    status: "Located and Open",
    lat: 6.849035,
    lng: 3.630761
  }
];
